version: '3.8'

services:
  ftps:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    env_file:
      - .env
    environment:
      PUBLICHOST: "127.0.0.1"
      FTP_PASSIVE_PORTS: "30000:30009"
      #ADDED_FLAGS: "-l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -R -P 127.0.0.1 -p 30000:30009 --tls=2 -c 5 -C 3"
    volumes:
      - ./data:/s3
      #- ./passwd:/etc/pure-ftpd/passwd
      - ./certs/pure-ftpd.pem:/etc/ssl/private/pure-ftpd.pem:ro
      - ./init-users.sh:/init-users.sh
    command: /bin/bash /init-users.sh
    restart: unless-stopped
